"""first migration

Revision ID: 62d2f1e41334
Revises: 
Create Date: 2025-08-20 12:33:04.546013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62d2f1e41334'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawing_processing_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('has_errors', sa.Boolean(), nullable=True),
    sa.Column('json_path', sa.String(), nullable=True),
    sa.Column('csv_path', sa.String(), nullable=True),
    sa.Column('extracted_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawing_processing_results_id'), 'drawing_processing_results', ['id'], unique=False)
    op.create_index(op.f('ix_drawing_processing_results_task_id'), 'drawing_processing_results', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drawing_processing_results_task_id'), table_name='drawing_processing_results')
    op.drop_index(op.f('ix_drawing_processing_results_id'), table_name='drawing_processing_results')
    op.drop_table('drawing_processing_results')
    # ### end Alembic commands ###
