"""create users table

Revision ID: 71053cc3f30d
Revises: 
Create Date: 2026-05-18 13:15:21.831551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71053cc3f30d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('stored_filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('output_path', sa.String(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_documents_id'), 'pdf_documents', ['id'], unique=False)
    op.create_index(op.f('ix_pdf_documents_task_id'), 'pdf_documents', ['task_id'], unique=True)
    op.create_table('page_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['pdf_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_contents_id'), 'page_contents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_contents_id'), table_name='page_contents')
    op.drop_table('page_contents')
    op.drop_index(op.f('ix_pdf_documents_task_id'), table_name='pdf_documents')
    op.drop_index(op.f('ix_pdf_documents_id'), table_name='pdf_documents')
    op.drop_table('pdf_documents')
    # ### end Alembic commands ###
