"""add csv

Revision ID: 79211e036256
Revises: f5dfe9332a1a
Create Date: 2025-09-10 15:05:26.494287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79211e036256'
down_revision: Union[str, Sequence[str], None] = 'f5dfe9332a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawing_processing_results', sa.Column('csv_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawing_processing_results', 'csv_path')
    # ### end Alembic commands ###
