"""remove csv_path column from drawing_processing_results

Revision ID: f5dfe9332a1a
Revises: 81efdf1cb163
Create Date: 2025-09-10 14:42:29.902528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5dfe9332a1a'
down_revision: Union[str, Sequence[str], None] = '81efdf1cb163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawing_processing_results', 'csv_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawing_processing_results', sa.Column('csv_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
